# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initContext <- function(threads = 1L) {
    .Call('_clustermq_initContext', PACKAGE = 'clustermq', threads)
}

initSocket <- function(context_, socket_type_) {
    .Call('_clustermq_initSocket', PACKAGE = 'clustermq', context_, socket_type_)
}

initMessage <- function(data_) {
    .Call('_clustermq_initMessage', PACKAGE = 'clustermq', data_)
}

bindSocket <- function(socket_, address) {
    invisible(.Call('_clustermq_bindSocket', PACKAGE = 'clustermq', socket_, address))
}

connectSocket <- function(socket_, address) {
    invisible(.Call('_clustermq_connectSocket', PACKAGE = 'clustermq', socket_, address))
}

disconnectSocket <- function(socket_, address) {
    invisible(.Call('_clustermq_disconnectSocket', PACKAGE = 'clustermq', socket_, address))
}

pollSocket <- function(sockets_, timeout = -1L) {
    .Call('_clustermq_pollSocket', PACKAGE = 'clustermq', sockets_, timeout)
}

receiveSocket <- function(socket_, dont_wait = FALSE, unserialize = TRUE) {
    .Call('_clustermq_receiveSocket', PACKAGE = 'clustermq', socket_, dont_wait, unserialize)
}

sendSocket <- function(socket_, data_, dont_wait = FALSE, send_more = FALSE) {
    invisible(.Call('_clustermq_sendSocket', PACKAGE = 'clustermq', socket_, data_, dont_wait, send_more))
}

